services:
  api:
    build: .
    container_name: url-shortener
    ports:
      - "127.0.0.1:8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: ${DEFAULT_CONNECTION_STRING}
      PageSize: ${PAGE_SIZE}
      JwtSettings__SecretKey: ${JWT_SECRET_KEY}
      JwtSettings__ExpirationTimeInMinutes: ${JWT_EXPIRATION_TIME_IN_MINUTES}
      JwtSettings__RefreshTokenExpirationTimeInDays: ${REFRESH_TOKEN_EXPIRATION_TIME_IN_DAYS}
      HashidsSalt: ${HASHIDS_SALT}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: url-shortener-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - url_shortener_pg_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432"
    restart: unless-stopped

volumes:
  url_shortener_pg_data: